# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: github pages


on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build

      #发布到mybells.github.io/master
      - name: Deploy janker0718.github.io/master
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          EXTERNAL_REPOSITORY: janker0718/janker0718.github.io #可以新建一个mybells.github.io仓库发布到master
          PUBLISH_BRANCH: master
          PUBLISH_DIR: docs/.vuepress/dist
        with:
          emptyCommits: false

